### ISSUE TITLE
Incorrect syntax hilighting of Ada character literals

### ISSUE THREAD

**Issue by faelys** [textmate/ada.tmbundle#3]
Hello,

I'm not a TextMate user, but it seems GitHub is using (a fork of) your bundle, and I notice the syntax hilighting problem in GitHub. I reported [the issue to linguist](https://github.com/github/linguist/issues/2357) and they redirected me here, so here is a copy of the problem.

To put it simply, it seems character literals in Ada are not recognized at all.

In Ada, much like in C, strings are arrays of characters, and string literals are written between double-quotes (`"`), while character literals are written between single-quotes (`'`). Escaping is a bit different than in C though: a double-quote character is inserted in a string literal using two consecutive double-quote character (e.g. `"This: "" is a single-double quote"`) while the character literal for the simple quote is three consecutive single-quotes (i.e. `'''`). To put it a regex way, character literals match `'.'` and the single-quote character literal is no exception.

As far as I can tell, there is currently no syntax hilighting at all for character literals. Here is an example:

```ada
declare
   Two_SL : String (1 .. 3) := "two";
   Two_CL : String (1 .. 3) := ('t', 'w', 'o');
begin
   Text_IO.Put_Line (Two_SL);
   Test_IO.Put_Line (Two_CL);
end;
```

As of this writing, `1` and `3` are colored specially, `"two"` has another color, `declare`, `begin` and `end` have keyword color, but `'t'` is in plain style like `Two_SL`.

Now in itself, it's a small problem, since character literals are small anyway. However it really hurts readability when using the double-quote character literal:

```ada
procedure Print_String_Value (Value : in String) is
begin
   Text_IO.Put_Line ("The value is: """ & Value & '"');
end Print_String_Value
```

For the reference, here `&` is the concatenation operators, and it is overloaded so that a string can be built by concatenating strings or by concatenating a string and a single character.

This causes the double-quote character literal to be considered as the beginning of a string literal, and the string coloring spans the rest of the code.

There are several real-world examples of this, [here is one of mine](https://github.com/faelys/markup-ada/blob/trunk/tools/markdown.adb#L120)

I wouldn't mind having character literals without special hilighting, if at least it wouldn't incorrectly color large sections of code.

Thanks for your time,
Natasha

**Comment by infininight** [comment]
Just deployed a fix for this, it will be available in TextMate within a few hours. It will be active on Github next time they deploy an update to linguist which is usually every few weeks.
